version: '3.5'
# have not configed network yet... in the future there will only
# be one scaled service with dynamic port assignment. 
services:
  dl3n-seeder:
    container_name: dl3n-seeder
    build: 
      context: .
      dockerfile: Dockerfile.dl3ndemo
    ports:
      - 3001:3000
    environment:
      - NODE_ID=dl3n-seeder
      - PEER_HOSTNAME=alpha
      - SUCCESSOR_LIST_SIZE=3
    depends_on:
      - alpha
      - bravo
      - charlie

  dl3n-getter:
    container_name: dl3n-getter
    build: 
      context: .
      dockerfile: Dockerfile.dl3ndemo
    ports:
      - 3002:3000
    environment:
      - NODE_ID=dl3n-getter
      - PEER_HOSTNAME=alpha
      - SUCCESSOR_LIST_SIZE=3
    depends_on:
      - alpha
      - bravo
      - charlie

  alpha:
    container_name: alpha
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000
    environment:
      - NODE_ID=alpha
      - PEER_HOSTNAME=
      - SUCCESSOR_LIST_SIZE=3
  bravo:
    container_name: nodeBravo
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000
    environment:
      - NODE_ID=nodeBravo
      - PEER_HOSTNAME=alpha
      - SUCCESSOR_LIST_SIZE=3
    restart: "no"
    depends_on:
      - alpha
  charlie:
    container_name: nodeCharlie
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000
    environment:
      - NODE_ID=nodeCharlie
      - PEER_HOSTNAME=alpha
      - SUCCESSOR_LIST_SIZE=3
    restart: "no"
    depends_on:
      - bravo
