version: '3.5'
# have not configed network yet... in the future there will only
# be one scaled service with dynamic port assignment.
services:
  panopticon:
    container_name: panopticon
    image: panopticon

  alpha:
    container_name: alpha
    image: chord_node
    ports:
      - 9000
    environment:
      - NODE_ID=alpha
      - PEER_HOSTNAME=
      - DEBUG=debug
  bravo:
    container_name: beta
    image: chord_node
    ports:
      - 9000
    environment:
      - NODE_ID=beta
      - PEER_HOSTNAME=alpha
      - DEBUG=debug
    restart: "no"
    depends_on:
      - alpha
  charlie:
    container_name: charlie
    image: chord_node
    ports:
      - 9000
    environment:
      - NODE_ID=charlie
      - PEER_HOSTNAME=alpha
      - DEBUG=debug
    depends_on:
      - alpha
    deploy:
      mode: replicated
      replicas: 1