version: '3.5'
# have not configed network yet... in the future there will only
# be one scaled service with dynamic port assignment. 
services:
  alpha:
    container_name: alpha
    image: chord_node
    ports:
      - 9000
    environment:
      - NODE_ID=alpha
      - PEER_HOSTNAME=
    restart: "no"
  bravo:
    container_name: bravo
    image: chord_node
    ports:
      - 9000
    environment:
      - NODE_ID=bravo
      - PEER_HOSTNAME=alpha
    restart: "no"
  charlie:
    container_name: charlie
    image: chord_node
    ports:
      - 9000
    environment:
      - NODE_ID=charlie
      - PEER_HOSTNAME=alpha
    restart: "no"