FROM golang AS builder
# stagedbuild

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o dl3n ./cmd/dl3n/dl3n.go

# using alpine for this, remember to use APK
FROM alpine
WORKDIR /built-app
COPY --from=builder /app/dl3n/dl3n /built-app/
# ENVARS
ENV NODE_ID=123
ENV PEER_HOSTNAME=godbless
EXPOSE 9000 8888

# do nothing
CMD sleep 86400