FROM golang:1.16-alpine

WORKDIR /app/src
COPY . .

# build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o dl3n ./cmd/dl3n/dl3n.go
RUN mv dl3n ../dl3n

WORKDIR /app
COPY ./dl3n/demo .
RUN rm -r src

EXPOSE 9000

# do nothing
CMD sleep 86400
