// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gossip

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalListenerClient is the client API for InternalListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalListenerClient interface {
	// core service
	Emit(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// chord file management services (internal)
	ReadFile(ctx context.Context, in *FetchChordRequest, opts ...grpc.CallOption) (*ContainerInfo, error)
	WriteFile(ctx context.Context, in *ModRequest, opts ...grpc.CallOption) (*ModResponse, error)
	WriteFileAndReplicate(ctx context.Context, in *ModRequest, opts ...grpc.CallOption) (*ModResponse, error)
	DeleteFile(ctx context.Context, in *FetchChordRequest, opts ...grpc.CallOption) (*ModResponse, error)
	FetchChordIp(ctx context.Context, in *FetchChordRequest, opts ...grpc.CallOption) (*ModResponse, error)
	MigrationJoin(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*MigrationResponse, error)
	MigrationFault(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*MigrationResponse, error)
	// D3L bridge protocol (external)
	StoreKeyHash(ctx context.Context, in *DLUploadRequest, opts ...grpc.CallOption) (*DLResponse, error)
	GetFileLocation(ctx context.Context, in *DLDownloadRequest, opts ...grpc.CallOption) (*DLDownloadResponse, error)
	Debug(ctx context.Context, in *DebugMessage, opts ...grpc.CallOption) (*DebugResponse, error)
}

type internalListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalListenerClient(cc grpc.ClientConnInterface) InternalListenerClient {
	return &internalListenerClient{cc}
}

func (c *internalListenerClient) Emit(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/Emit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) ReadFile(ctx context.Context, in *FetchChordRequest, opts ...grpc.CallOption) (*ContainerInfo, error) {
	out := new(ContainerInfo)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/ReadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) WriteFile(ctx context.Context, in *ModRequest, opts ...grpc.CallOption) (*ModResponse, error) {
	out := new(ModResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/WriteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) WriteFileAndReplicate(ctx context.Context, in *ModRequest, opts ...grpc.CallOption) (*ModResponse, error) {
	out := new(ModResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/WriteFileAndReplicate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) DeleteFile(ctx context.Context, in *FetchChordRequest, opts ...grpc.CallOption) (*ModResponse, error) {
	out := new(ModResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) FetchChordIp(ctx context.Context, in *FetchChordRequest, opts ...grpc.CallOption) (*ModResponse, error) {
	out := new(ModResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/FetchChordIp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) MigrationJoin(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*MigrationResponse, error) {
	out := new(MigrationResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/MigrationJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) MigrationFault(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*MigrationResponse, error) {
	out := new(MigrationResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/MigrationFault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) StoreKeyHash(ctx context.Context, in *DLUploadRequest, opts ...grpc.CallOption) (*DLResponse, error) {
	out := new(DLResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/StoreKeyHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) GetFileLocation(ctx context.Context, in *DLDownloadRequest, opts ...grpc.CallOption) (*DLDownloadResponse, error) {
	out := new(DLDownloadResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/GetFileLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalListenerClient) Debug(ctx context.Context, in *DebugMessage, opts ...grpc.CallOption) (*DebugResponse, error) {
	out := new(DebugResponse)
	err := c.cc.Invoke(ctx, "/internal.InternalListener/Debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalListenerServer is the server API for InternalListener service.
// All implementations must embed UnimplementedInternalListenerServer
// for forward compatibility
type InternalListenerServer interface {
	// core service
	Emit(context.Context, *Request) (*Response, error)
	// chord file management services (internal)
	ReadFile(context.Context, *FetchChordRequest) (*ContainerInfo, error)
	WriteFile(context.Context, *ModRequest) (*ModResponse, error)
	WriteFileAndReplicate(context.Context, *ModRequest) (*ModResponse, error)
	DeleteFile(context.Context, *FetchChordRequest) (*ModResponse, error)
	FetchChordIp(context.Context, *FetchChordRequest) (*ModResponse, error)
	MigrationJoin(context.Context, *MigrationRequest) (*MigrationResponse, error)
	MigrationFault(context.Context, *MigrationRequest) (*MigrationResponse, error)
	// D3L bridge protocol (external)
	StoreKeyHash(context.Context, *DLUploadRequest) (*DLResponse, error)
	GetFileLocation(context.Context, *DLDownloadRequest) (*DLDownloadResponse, error)
	Debug(context.Context, *DebugMessage) (*DebugResponse, error)
	mustEmbedUnimplementedInternalListenerServer()
}

// UnimplementedInternalListenerServer must be embedded to have forward compatible implementations.
type UnimplementedInternalListenerServer struct {
}

func (UnimplementedInternalListenerServer) Emit(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedInternalListenerServer) ReadFile(context.Context, *FetchChordRequest) (*ContainerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedInternalListenerServer) WriteFile(context.Context, *ModRequest) (*ModResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedInternalListenerServer) WriteFileAndReplicate(context.Context, *ModRequest) (*ModResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFileAndReplicate not implemented")
}
func (UnimplementedInternalListenerServer) DeleteFile(context.Context, *FetchChordRequest) (*ModResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedInternalListenerServer) FetchChordIp(context.Context, *FetchChordRequest) (*ModResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchChordIp not implemented")
}
func (UnimplementedInternalListenerServer) MigrationJoin(context.Context, *MigrationRequest) (*MigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrationJoin not implemented")
}
func (UnimplementedInternalListenerServer) MigrationFault(context.Context, *MigrationRequest) (*MigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrationFault not implemented")
}
func (UnimplementedInternalListenerServer) StoreKeyHash(context.Context, *DLUploadRequest) (*DLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreKeyHash not implemented")
}
func (UnimplementedInternalListenerServer) GetFileLocation(context.Context, *DLDownloadRequest) (*DLDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileLocation not implemented")
}
func (UnimplementedInternalListenerServer) Debug(context.Context, *DebugMessage) (*DebugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debug not implemented")
}
func (UnimplementedInternalListenerServer) mustEmbedUnimplementedInternalListenerServer() {}

// UnsafeInternalListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalListenerServer will
// result in compilation errors.
type UnsafeInternalListenerServer interface {
	mustEmbedUnimplementedInternalListenerServer()
}

func RegisterInternalListenerServer(s grpc.ServiceRegistrar, srv InternalListenerServer) {
	s.RegisterService(&InternalListener_ServiceDesc, srv)
}

func _InternalListener_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/Emit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).Emit(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchChordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/ReadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).ReadFile(ctx, req.(*FetchChordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/WriteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).WriteFile(ctx, req.(*ModRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_WriteFileAndReplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).WriteFileAndReplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/WriteFileAndReplicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).WriteFileAndReplicate(ctx, req.(*ModRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchChordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).DeleteFile(ctx, req.(*FetchChordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_FetchChordIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchChordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).FetchChordIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/FetchChordIp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).FetchChordIp(ctx, req.(*FetchChordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_MigrationJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).MigrationJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/MigrationJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).MigrationJoin(ctx, req.(*MigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_MigrationFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).MigrationFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/MigrationFault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).MigrationFault(ctx, req.(*MigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_StoreKeyHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DLUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).StoreKeyHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/StoreKeyHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).StoreKeyHash(ctx, req.(*DLUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_GetFileLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DLDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).GetFileLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/GetFileLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).GetFileLocation(ctx, req.(*DLDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalListener_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.InternalListener/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).Debug(ctx, req.(*DebugMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalListener_ServiceDesc is the grpc.ServiceDesc for InternalListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.InternalListener",
	HandlerType: (*InternalListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _InternalListener_Emit_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _InternalListener_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _InternalListener_WriteFile_Handler,
		},
		{
			MethodName: "WriteFileAndReplicate",
			Handler:    _InternalListener_WriteFileAndReplicate_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _InternalListener_DeleteFile_Handler,
		},
		{
			MethodName: "FetchChordIp",
			Handler:    _InternalListener_FetchChordIp_Handler,
		},
		{
			MethodName: "MigrationJoin",
			Handler:    _InternalListener_MigrationJoin_Handler,
		},
		{
			MethodName: "MigrationFault",
			Handler:    _InternalListener_MigrationFault_Handler,
		},
		{
			MethodName: "StoreKeyHash",
			Handler:    _InternalListener_StoreKeyHash_Handler,
		},
		{
			MethodName: "GetFileLocation",
			Handler:    _InternalListener_GetFileLocation_Handler,
		},
		{
			MethodName: "Debug",
			Handler:    _InternalListener_Debug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/internal.proto",
}
