// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: proto/internal.proto

package grpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Command int32

const (
	Command_FIND_SUCCESSOR  Command = 0
	Command_JOIN            Command = 1
	Command_HEALTHCHECK     Command = 2
	Command_GET_PREDECESSOR Command = 3
	Command_NOTIFY          Command = 4
	Command_LOOKUP          Command = 5
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "FIND_SUCCESSOR",
		1: "JOIN",
		2: "HEALTHCHECK",
		3: "GET_PREDECESSOR",
		4: "NOTIFY",
		5: "LOOKUP",
	}
	Command_value = map[string]int32{
		"FIND_SUCCESSOR":  0,
		"JOIN":            1,
		"HEALTHCHECK":     2,
		"GET_PREDECESSOR": 3,
		"NOTIFY":          4,
		"LOOKUP":          5,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_internal_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_proto_internal_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command     Command              `protobuf:"varint,1,opt,name=command,proto3,enum=grpc.Command" json:"command,omitempty"`
	RequesterID string               `protobuf:"bytes,2,opt,name=requesterID,proto3" json:"requesterID,omitempty"`
	TargetID    string               `protobuf:"bytes,3,opt,name=targetID,proto3" json:"targetID,omitempty"`
	Body        *Request_RequestBody `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_FIND_SUCCESSOR
}

func (x *Request) GetRequesterID() string {
	if x != nil {
		return x.RequesterID
	}
	return ""
}

func (x *Request) GetTargetID() string {
	if x != nil {
		return x.TargetID
	}
	return ""
}

func (x *Request) GetBody() *Request_RequestBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command     Command               `protobuf:"varint,1,opt,name=command,proto3,enum=grpc.Command" json:"command,omitempty"`
	RequesterID string                `protobuf:"bytes,2,opt,name=requesterID,proto3" json:"requesterID,omitempty"`
	TargetID    string                `protobuf:"bytes,3,opt,name=targetID,proto3" json:"targetID,omitempty"`
	Body        *Response_RequestBody `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_FIND_SUCCESSOR
}

func (x *Response) GetRequesterID() string {
	if x != nil {
		return x.RequesterID
	}
	return ""
}

func (x *Response) GetTargetID() string {
	if x != nil {
		return x.TargetID
	}
	return ""
}

func (x *Response) GetBody() *Response_RequestBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type Request_RequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FindSuccessor  *Request_KeySlotBody  `protobuf:"bytes,1,opt,name=FindSuccessor,proto3" json:"FindSuccessor,omitempty"`
	Join           *Request_NullBody     `protobuf:"bytes,2,opt,name=Join,proto3" json:"Join,omitempty"`
	Healthcheck    *Request_NullBody     `protobuf:"bytes,3,opt,name=Healthcheck,proto3" json:"Healthcheck,omitempty"`
	GetPredecessor *Request_NullBody     `protobuf:"bytes,4,opt,name=GetPredecessor,proto3" json:"GetPredecessor,omitempty"`
	Notify         *Request_NullBody     `protobuf:"bytes,5,opt,name=Notify,proto3" json:"Notify,omitempty"`
	Lookup         *Request_InfoHashBody `protobuf:"bytes,6,opt,name=Lookup,proto3" json:"Lookup,omitempty"`
}

func (x *Request_RequestBody) Reset() {
	*x = Request_RequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_RequestBody) ProtoMessage() {}

func (x *Request_RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_RequestBody.ProtoReflect.Descriptor instead.
func (*Request_RequestBody) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_RequestBody) GetFindSuccessor() *Request_KeySlotBody {
	if x != nil {
		return x.FindSuccessor
	}
	return nil
}

func (x *Request_RequestBody) GetJoin() *Request_NullBody {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *Request_RequestBody) GetHealthcheck() *Request_NullBody {
	if x != nil {
		return x.Healthcheck
	}
	return nil
}

func (x *Request_RequestBody) GetGetPredecessor() *Request_NullBody {
	if x != nil {
		return x.GetPredecessor
	}
	return nil
}

func (x *Request_RequestBody) GetNotify() *Request_NullBody {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *Request_RequestBody) GetLookup() *Request_InfoHashBody {
	if x != nil {
		return x.Lookup
	}
	return nil
}

type Request_KeySlotBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeySlot int64 `protobuf:"varint,1,opt,name=KeySlot,proto3" json:"KeySlot,omitempty"`
}

func (x *Request_KeySlotBody) Reset() {
	*x = Request_KeySlotBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_KeySlotBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_KeySlotBody) ProtoMessage() {}

func (x *Request_KeySlotBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_KeySlotBody.ProtoReflect.Descriptor instead.
func (*Request_KeySlotBody) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Request_KeySlotBody) GetKeySlot() int64 {
	if x != nil {
		return x.KeySlot
	}
	return 0
}

type Request_InfoHashBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfoHash string `protobuf:"bytes,1,opt,name=InfoHash,proto3" json:"InfoHash,omitempty"`
}

func (x *Request_InfoHashBody) Reset() {
	*x = Request_InfoHashBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_InfoHashBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_InfoHashBody) ProtoMessage() {}

func (x *Request_InfoHashBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_InfoHashBody.ProtoReflect.Descriptor instead.
func (*Request_InfoHashBody) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Request_InfoHashBody) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

type Request_NullBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request_NullBody) Reset() {
	*x = Request_NullBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_NullBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_NullBody) ProtoMessage() {}

func (x *Request_NullBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_NullBody.ProtoReflect.Descriptor instead.
func (*Request_NullBody) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0, 3}
}

type Response_RequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FindSuccessor  *Response_IDBody      `protobuf:"bytes,1,opt,name=FindSuccessor,proto3" json:"FindSuccessor,omitempty"`
	Join           *Response_IDBody      `protobuf:"bytes,2,opt,name=Join,proto3" json:"Join,omitempty"`
	Healthcheck    *Response_SuccessBody `protobuf:"bytes,3,opt,name=Healthcheck,proto3" json:"Healthcheck,omitempty"`
	GetPredecessor *Response_IDBody      `protobuf:"bytes,4,opt,name=GetPredecessor,proto3" json:"GetPredecessor,omitempty"`
	Notify         *Response_SuccessBody `protobuf:"bytes,5,opt,name=Notify,proto3" json:"Notify,omitempty"`
	Lookup         *Response_DataBody    `protobuf:"bytes,6,opt,name=Lookup,proto3" json:"Lookup,omitempty"`
}

func (x *Response_RequestBody) Reset() {
	*x = Response_RequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_RequestBody) ProtoMessage() {}

func (x *Response_RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_RequestBody.ProtoReflect.Descriptor instead.
func (*Response_RequestBody) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Response_RequestBody) GetFindSuccessor() *Response_IDBody {
	if x != nil {
		return x.FindSuccessor
	}
	return nil
}

func (x *Response_RequestBody) GetJoin() *Response_IDBody {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *Response_RequestBody) GetHealthcheck() *Response_SuccessBody {
	if x != nil {
		return x.Healthcheck
	}
	return nil
}

func (x *Response_RequestBody) GetGetPredecessor() *Response_IDBody {
	if x != nil {
		return x.GetPredecessor
	}
	return nil
}

func (x *Response_RequestBody) GetNotify() *Response_SuccessBody {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *Response_RequestBody) GetLookup() *Response_DataBody {
	if x != nil {
		return x.Lookup
	}
	return nil
}

type Response_IDBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *Response_IDBody) Reset() {
	*x = Response_IDBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_IDBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_IDBody) ProtoMessage() {}

func (x *Response_IDBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_IDBody.ProtoReflect.Descriptor instead.
func (*Response_IDBody) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Response_IDBody) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Response_DataBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []string `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	IsErr bool     `protobuf:"varint,2,opt,name=IsErr,proto3" json:"IsErr,omitempty"`
}

func (x *Response_DataBody) Reset() {
	*x = Response_DataBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_DataBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_DataBody) ProtoMessage() {}

func (x *Response_DataBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_DataBody.ProtoReflect.Descriptor instead.
func (*Response_DataBody) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Response_DataBody) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response_DataBody) GetIsErr() bool {
	if x != nil {
		return x.IsErr
	}
	return false
}

type Response_SuccessBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *Response_SuccessBody) Reset() {
	*x = Response_SuccessBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_SuccessBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_SuccessBody) ProtoMessage() {}

func (x *Response_SuccessBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_SuccessBody.ProtoReflect.Descriptor instead.
func (*Response_SuccessBody) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Response_SuccessBody) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_internal_proto protoreflect.FileDescriptor

var file_proto_internal_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xdb, 0x04, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12,
	0x2d, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0xd8,
	0x02, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x3f,
	0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12,
	0x2a, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x75, 0x6c,
	0x6c, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4e, 0x75, 0x6c, 0x6c, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x3e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64,
	0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x75, 0x6c,
	0x6c, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x06, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x32, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x64,
	0x79, 0x52, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x1a, 0x27, 0x0a, 0x0b, 0x4b, 0x65, 0x79,
	0x53, 0x6c, 0x6f, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x53,
	0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4b, 0x65, 0x79, 0x53, 0x6c,
	0x6f, 0x74, 0x1a, 0x2a, 0x0a, 0x0c, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x0a,
	0x0a, 0x08, 0x4e, 0x75, 0x6c, 0x6c, 0x42, 0x6f, 0x64, 0x79, 0x22, 0xf4, 0x04, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12, 0x2e,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0xd7,
	0x02, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x3b,
	0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x44, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x0d, 0x46, 0x69,
	0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x4a,
	0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x44, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x3c, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x12, 0x3d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x44, 0x42,
	0x6f, 0x64, 0x79, 0x52, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x64, 0x79, 0x52,
	0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x2f, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x1a, 0x18, 0x0a, 0x06, 0x49, 0x44, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x1a, 0x34, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x45, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x49, 0x73, 0x45, 0x72, 0x72, 0x1a, 0x27, 0x0a, 0x0b, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x2a, 0x65, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x0e,
	0x46, 0x49, 0x4e, 0x44, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x4f, 0x52, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x45,
	0x41, 0x4c, 0x54, 0x48, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x47,
	0x45, 0x54, 0x5f, 0x50, 0x52, 0x45, 0x44, 0x45, 0x43, 0x45, 0x53, 0x53, 0x4f, 0x52, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06,
	0x4c, 0x4f, 0x4f, 0x4b, 0x55, 0x50, 0x10, 0x05, 0x32, 0x3b, 0x0a, 0x10, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x04,
	0x45, 0x6d, 0x69, 0x74, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x65, 0x69, 0x6b, 0x68, 0x73, 0x68, 0x61, 0x63, 0x6b, 0x2f,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x63, 0x68, 0x61, 0x6f,
	0x73, 0x2d, 0x35, 0x30, 0x2e, 0x30, 0x34, 0x31, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_internal_proto_rawDescOnce sync.Once
	file_proto_internal_proto_rawDescData = file_proto_internal_proto_rawDesc
)

func file_proto_internal_proto_rawDescGZIP() []byte {
	file_proto_internal_proto_rawDescOnce.Do(func() {
		file_proto_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_internal_proto_rawDescData)
	})
	return file_proto_internal_proto_rawDescData
}

var file_proto_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_internal_proto_goTypes = []interface{}{
	(Command)(0),                 // 0: grpc.Command
	(*Request)(nil),              // 1: grpc.Request
	(*Response)(nil),             // 2: grpc.Response
	(*Request_RequestBody)(nil),  // 3: grpc.Request.RequestBody
	(*Request_KeySlotBody)(nil),  // 4: grpc.Request.KeySlotBody
	(*Request_InfoHashBody)(nil), // 5: grpc.Request.InfoHashBody
	(*Request_NullBody)(nil),     // 6: grpc.Request.NullBody
	(*Response_RequestBody)(nil), // 7: grpc.Response.RequestBody
	(*Response_IDBody)(nil),      // 8: grpc.Response.IDBody
	(*Response_DataBody)(nil),    // 9: grpc.Response.DataBody
	(*Response_SuccessBody)(nil), // 10: grpc.Response.SuccessBody
}
var file_proto_internal_proto_depIdxs = []int32{
	0,  // 0: grpc.Request.command:type_name -> grpc.Command
	3,  // 1: grpc.Request.body:type_name -> grpc.Request.RequestBody
	0,  // 2: grpc.Response.command:type_name -> grpc.Command
	7,  // 3: grpc.Response.body:type_name -> grpc.Response.RequestBody
	4,  // 4: grpc.Request.RequestBody.FindSuccessor:type_name -> grpc.Request.KeySlotBody
	6,  // 5: grpc.Request.RequestBody.Join:type_name -> grpc.Request.NullBody
	6,  // 6: grpc.Request.RequestBody.Healthcheck:type_name -> grpc.Request.NullBody
	6,  // 7: grpc.Request.RequestBody.GetPredecessor:type_name -> grpc.Request.NullBody
	6,  // 8: grpc.Request.RequestBody.Notify:type_name -> grpc.Request.NullBody
	5,  // 9: grpc.Request.RequestBody.Lookup:type_name -> grpc.Request.InfoHashBody
	8,  // 10: grpc.Response.RequestBody.FindSuccessor:type_name -> grpc.Response.IDBody
	8,  // 11: grpc.Response.RequestBody.Join:type_name -> grpc.Response.IDBody
	10, // 12: grpc.Response.RequestBody.Healthcheck:type_name -> grpc.Response.SuccessBody
	8,  // 13: grpc.Response.RequestBody.GetPredecessor:type_name -> grpc.Response.IDBody
	10, // 14: grpc.Response.RequestBody.Notify:type_name -> grpc.Response.SuccessBody
	9,  // 15: grpc.Response.RequestBody.Lookup:type_name -> grpc.Response.DataBody
	1,  // 16: grpc.InternalListener.Emit:input_type -> grpc.Request
	2,  // 17: grpc.InternalListener.Emit:output_type -> grpc.Response
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_internal_proto_init() }
func file_proto_internal_proto_init() {
	if File_proto_internal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_RequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_KeySlotBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_InfoHashBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_NullBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_RequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_IDBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_DataBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_SuccessBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_internal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_internal_proto_goTypes,
		DependencyIndexes: file_proto_internal_proto_depIdxs,
		EnumInfos:         file_proto_internal_proto_enumTypes,
		MessageInfos:      file_proto_internal_proto_msgTypes,
	}.Build()
	File_proto_internal_proto = out.File
	file_proto_internal_proto_rawDesc = nil
	file_proto_internal_proto_goTypes = nil
	file_proto_internal_proto_depIdxs = nil
}
