// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalListenerClient is the client API for InternalListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalListenerClient interface {
	Emit(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type internalListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalListenerClient(cc grpc.ClientConnInterface) InternalListenerClient {
	return &internalListenerClient{cc}
}

func (c *internalListenerClient) Emit(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.InternalListener/Emit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalListenerServer is the server API for InternalListener service.
// All implementations must embed UnimplementedInternalListenerServer
// for forward compatibility
type InternalListenerServer interface {
	Emit(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedInternalListenerServer()
}

// UnimplementedInternalListenerServer must be embedded to have forward compatible implementations.
type UnimplementedInternalListenerServer struct {
}

func (UnimplementedInternalListenerServer) Emit(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedInternalListenerServer) mustEmbedUnimplementedInternalListenerServer() {}

// UnsafeInternalListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalListenerServer will
// result in compilation errors.
type UnsafeInternalListenerServer interface {
	mustEmbedUnimplementedInternalListenerServer()
}

func RegisterInternalListenerServer(s grpc.ServiceRegistrar, srv InternalListenerServer) {
	s.RegisterService(&InternalListener_ServiceDesc, srv)
}

func _InternalListener_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalListenerServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.InternalListener/Emit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalListenerServer).Emit(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalListener_ServiceDesc is the grpc.ServiceDesc for InternalListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.InternalListener",
	HandlerType: (*InternalListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _InternalListener_Emit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/internal.proto",
}
